version: '3.8'
services:
  app:
    build: ./webapp/
    command: python -u interface/main.py
    # command: gunicorn --bind 0.0.0.0:5000 --keyfile /usr/src/app/myserver.key --certfile /usr/src/app/olsm_ddns_net.pem --chdir interface/ main:app
    ports:
      - 443:5000
    links:
      - db
      - model
    volumes:
      - ./webapp:/usr/src/app
  model:
    build: ./modelapp/
    command: python -u model/app.py
    # command: gunicorn --bind 0.0.0.0:8000 --keyfile /usr/src/app/myserver.key --certfile /usr/src/app/olsm_ddns_net.pem --chdir model/ app:app
    ports:
      - 8000:8000
    links:
      - db
    volumes:
      - ./modelapp:/usr/src/app
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=olsm_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017
